### ISSUE TITLE
Do not re-compile a file if it is already up-to-date

### ISSUE THREAD

**Issue by AnthonyBuisset** [open-dust/cairo-foundry#11]
The compiler module will be shared by multiple commands (list tests, execute test, etc).
It would be nice to avoid multiple compilations if the compiled program is up-to-date (generated after) the program itself.
It will increase UX in the following scenarii:
   - list test several times in a row
   - list test then execute one of them in a row

How to?
Check file system timestamps

**Comment by internnos** [comment]
i'm thinking of using `hash` or `git diff`

what do you think about it?
