### ISSUE TITLE
prevent infinite loop in tests

### ISSUE THREAD

**Issue by tdelabro** [open-dust/cairo-foundry#43]
Right now if a test contains an infinite loop, it will endlessly loop.
We should cap the time we want to spend on each test and stop the test if this time is exceeded.

We can take a --max-step argument in the CLI, with a default value so that if not passed it will still be one.

Then we can check the current number of steps (already recorded in `vm.current_step`) against a max step value we initialized inside the`execution_scopes`

**Comment by hurrikaanig** [comment]
Can I get assigned to this 😁

**Comment by tdelabro** [comment]
Hey @hurrikaanig , how are things going with this one? Did you solved your problem with the cairoVM?
Can I help you?

**Comment by hurrikaanig** [comment]
Hey ! The getter for current_step got merged last saturday, so it should be good now. I'll continue working on this today

**Comment by tdelabro** [comment]
closed by #110
