### ISSUE TITLE
Doc - Describe `cairo_run` using Rustdoc comments (three slashes: ///)

### ISSUE THREAD

**Issue by Eikix** [open-dust/cairo-foundry#52]
In an effort of having fully documented code, we need our cairo runner to be documented.

Please proceed to comment above the `pub fn cairo_run` declaration in an equivalent way as `pub fn compile` is documented.

**Comment by ptisserand** [comment]
Hi, can I work on this issue?

**Comment by Eikix** [comment]
Sure thing!
