### ISSUE TITLE
Doc - Describe `expect_revert` using Rustdoc comments (three slashes: ///) 

### ISSUE THREAD

**Issue by Eikix** [open-dust/cairo-foundry#56]
In an effort of having fully documented code, we need the way we expect reverted calls to be documented.

In src/hints/expect_revert, please proceed to comment above the `pub fn expect_revert` declaration in an equivalent way as `pub fn compile` is documented.

**Comment by bacharif** [comment]
I take

**Comment by tdelabro** [comment]
closed by #95
