### ISSUE TITLE
Doc - Describe `list_test_entrypoints` using Rustdoc comments (three slashes: ///)

### ISSUE THREAD

**Issue by Eikix** [open-dust/cairo-foundry#57]
In an effort of having fully documented code, we need the way we list entry points in a Cairo repository to be documented.

In src/cli/commands/test, please proceed to comment above the `fn list_test_entrypoints` declaration in an equivalent way as `pub fn compile` is documented.

**Comment by gdnathan** [comment]
I'd like to contribute on this issue
