### ISSUE TITLE
Doc - Describe src/cli/commands/test uncommented functions using Rustdoc comments (three slashes: ///) #52

### ISSUE THREAD

**Issue by Eikix** [open-dust/cairo-foundry#59]
In an effort of having fully documented code, we need the functions that run during a test run to be documented.

In src/cli/commands/test, please proceed to comment above the `fn setup_hooks`, `fn list_cairo_files`, `compile_and_list_entrypoints` and `purge_hint_buffer` declarations in an equivalent way as `pub fn compile` is documented.

**Comment by baipaiha** [comment]
Hi, i would like to contribute on this

**Comment by tdelabro** [comment]
Hey @baipaiha , how are things going with this one? Can we help you in any way ?
