### ISSUE TITLE
Doc - Describe `test_single_entrypoint` using Rustdoc comments (three slashes: ///) 

### ISSUE THREAD

**Issue by Eikix** [open-dust/cairo-foundry#60]
In an effort of having fully documented code, we need the way we run tests on a single Cairo entry point to be documented.

In src/cli/commands/test, please proceed to comment above the `pub(crate) fn test_single_entrypoint` declaration in an equivalent way as `pub fn compile` is documented.

**Comment by gdnathan** [comment]
I'd like to contribute on this issue
