### ISSUE TITLE
Doc - Describe `run_tests_for_one_file` using Rustdoc comments (three slashes: ///) 

### ISSUE THREAD

**Issue by Eikix** [open-dust/cairo-foundry#61]
In an effort of having fully documented code, we need the way we run tests for a single file to be documented.

In src/cli/commands/test, please proceed to comment above the `fn run_tests_for_one_file` declaration in an equivalent way as `pub fn compile` is documented.

**Comment by gdnathan** [comment]
I'd like to contribute on this issue
