### ISSUE TITLE
Doc - Describe `src > cli > commands > list` functions and modules using Rustdoc comments (three slashes: ///) 

### ISSUE THREAD

**Issue by Eikix** [open-dust/cairo-foundry#62]
In an effort of having fully documented code, we need the way we list files in a repository to be documented.

In src > cli > commands > list, please proceed to comment above the functions and modules declarations in an equivalent way as `pub fn compile` is documented.

**Comment by jdembdr** [comment]
Hi, I'd like to contribute on this

**Comment by tdelabro** [comment]
closed by #71
