### ISSUE TITLE
create a `clean` command

### ISSUE THREAD

**Issue by tdelabro** [open-dust/cairo-foundry#68]
cairo-foundry caches stuff during its execution:
- the compiled files
- files that contain hash of the cairo files in order to avoid recompilation

Those are never deleted.

We should introduce a `clean` command. When executed it deletes the whole cache.

**Comment by sleepyqadir** [comment]
@tdelabro can you assign me this issue, I can work on it

**Comment by sleepyqadir** [comment]
@tdelabro , any reference code or anything on where i can find files that contain hash of cairo files.

**Comment by sleepyqadir** [comment]
@tdelabro, any reference code or anything on where I can find files that contain the hash of Cairo files?

**Comment by Eikix** [comment]
@internnos is currently working [on a PR](https://github.com/onlydustxyz/cairo-foundry/pull/66) that enables caching.
I believe he's working with the conventional cache_dir paths: https://doc.rust-lang.org/cargo/guide/build-cache.html / https://docs.rs/dirs/latest/dirs/fn.cache_dir.html

**Comment by internnos** [comment]
yep thanks @Eikix for the ping!

you can read the PR here #66 

currently its a work in progress but you get the general idea

**Comment by sleepyqadir** [comment]
@internnos great thanks, I'll look into it for reference

**Comment by tdelabro** [comment]
closed by #116
