### ISSUE TITLE
Create an `after_step_instruction` hook - akin to `pre_step_instruction`

### ISSUE THREAD

**Issue by Eikix** [open-dust/cairo-foundry#74]
We aim to create a DX-friendly testing experience. To achieve that, we'll need to access important moments of the execution process. 
Namely, we'd like to have these known test utils: `beforeAll`, `afterAll`, `beforeEach` ( ✅ we have this `pre_step_instruction`), afterEach

The `after_step_instruction` hook would be the equivalent of `afterEach` and similar hooks. It would run after every step of your process (per test function, i.e. per run). It does not need to execute hints (such as mocking etc.) just yet.

The aim of this issue is to invest brain power in proposing a sound strategy to properly hook into this particular step of the execution process.

**Comment by ptisserand** [comment]
I'm wondering how we could manage the dependency with cairo-rs source code modification:should we report an issue in cairo-rs and link it here ?
By the way, I can work on this issue ;)

**Comment by Eikix** [comment]
My understanding is that we're using a specific fork for our hooks:

https://github.com/open-dust/cairo-rs/tree/main

So we'd add the specific feature there

**Comment by ptisserand** [comment]
I think we should keep the same signature as `pre_step_instruction` hook:
```rust
type PreStepInstructionHook = Arc<
    dyn Fn(
            &mut VirtualMachine,
            &mut ExecutionScopes,
            &HashMap<String, BigInt>,
        ) -> Result<(), VirtualMachineError>
        + Sync
        + Send,
>;
```

About the name, I think we should use `post_step_instruction` instead of `after_step_instruction` to be consistent with `pre_step_instruction`

**Comment by Eikix** [comment]
> I think we should keep the same signature as `pre_step_instruction` hook:
> ```rust
> type PreStepInstructionHook = Arc<
>     dyn Fn(
>             &mut VirtualMachine,
>             &mut ExecutionScopes,
>             &HashMap<String, BigInt>,
>         ) -> Result<(), VirtualMachineError>
>         + Sync
>         + Send,
> >;
> ```
> 
> About the name, I think we should use `post_step_instruction` instead of `after_step_instruction` to be consistent with `pre_step_instruction`

Good point ! Agreed

**Comment by ptisserand** [comment]
Here is the link to cairo-foundry pull request to add `post_step_instruction` hook: https://github.com/open-dust/cairo-rs/pull/8
