### ISSUE TITLE
Fix: fix cairo-rs dependency after main branch rebase 

### ISSUE THREAD

**Issue by Eikix** [open-dust/cairo-foundry#90]
On the January 4th, @Eikix rebased the open-dust cairo-rs fork, cairo-foundry branch.
It appears it broke the build process of the repository cairo-foundry.

@ptisserand offered to try and debug it.

**Comment by ptisserand** [comment]
Build issues appears when switching revisions:
```diff
-source = "git+https://github.com/onlydustxyz/cairo-rs?branch=cairo-foundry#c066cfac5f1f484841dd3abf5cb48b1e93a04b0e"
+source = "git+https://github.com/onlydustxyz/cairo-rs?branch=cairo-foundry#903950f23cb3670dd30f759d5f6cb8f60ce28d1a"
```

**Comment by ptisserand** [comment]
For the record, cairo-rs previous cairo-foundry branch commit was based on https://github.com/lambdaclass/cairo-rs/tree/b99f77f65156394b7e4a7c1dd52839e28f45ccbf

Here are the modifications done between b99f77f65156394b7e4a7c1dd52839e28f45ccbf and c066cfac5f1f484841dd3abf5cb48b1e93a04b0e:
- [Logs between cairo-rs `main` and `cairo-foundry` branch](https://github.com/open-dust/cairo-foundry/files/10358692/logs-modifications-cairo_foundry.log)
- [Differences between cairo-rs `main` and `cairo-foundry` branch](https://github.com/open-dust/cairo-foundry/files/10358696/modifications-cairo_foundry.patch.txt)
