### ISSUE TITLE
skip hint is no more functional after cairo-rs update

### ISSUE THREAD

**Issue by ptisserand** [open-dust/cairo-foundry#93]
After updating cairo-rs, it seems that "skip" hint is no more functionnal.

Here is the output of `cairo-foundry test`:
```
$ ./target/debug/cairo-foundry test
Error: binary '/home/robin/cairo_venv/bin/cairo-compile' failed to compile './test_cairo_contracts/test_invalid_program.cairo:18:17: Unknown identifier '__main__.balance.read'.
    let (res) = balance.read();
                ^**********^
'
Error: An ASSERT_EQ instruction failed: 50 != 55.
Error: An ASSERT_EQ instruction failed: 3 != 2.
Running tests in file ./test_cairo_hints/test_mock_call.cairo
[OK] test_mock_call (543.961µs)


Error: Got an exception while executing a hint: Custom Hint Error: skip
```

Maybe it's related to the following info in the changelog:
[`VirtualMachineError`s produced by `HintProcessor::execute_hint()` will be wrapped in a `VirtualMachineError::Hint` error containing their hint_index](https://github.com/open-dust/cairo-rs/blob/cairo-foundry/CHANGELOG.md?plain=1#L18)
https://github.com/lambdaclass/cairo-rs/pull/673/files

**Comment by ptisserand** [comment]
[Q&D workaround](https://github.com/open-dust/cairo-foundry/files/10371793/cairo-foundry.patch.txt)

**Comment by tdelabro** [comment]
Look like it is now. Thanks @ptisserand
